version: "2"

services:
  kafka:
    container_name: ias-kafka
    image: alarmsystem/ias-kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092

  alma-weather-plugin:
    container_name: ias-prod-alma-weather-plugin
    image: registry.inria.cl:5000/alma-weather-plugin:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  converter:
    container_name: ias-prod-converter
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  supervisor:
    container_name: ias-prod-supervisor
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor SupervisorID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  weather-supervisor:
    container_name: ias-prod-weather-supervisor
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor Supervisor-Weather -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-prod-sender
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
      - ${CDB_PATH}:/usr/src/cdb
    command: "iasRun -l j -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8001/core/ org.eso.ias.webserversender.WebServerSender WebServerSenderID -jcdb /usr/src/cdb/"

  webserver:
    container_name: ias-prod-webserver
    image: registry.inria.cl:5000/ias-webserver:prod
    command: ./runserver.sh

  display:
    container_name: ias-prod-display
    image: registry.inria.cl:5000/ias-display:prod

  nginx:
    container_name: ias-prod-nginx
    build: ${DOCKERFILE_PATH_NGINX}
    volumes_from:
      - display
      - webserver
    links:
      - display
      - webserver
    depends_on:
      - display
      - webserver
    ports:
      - "80:80"
