version: "2"

services:
  kafka:
    container_name: ias-prod
    build: ${DOCKERFILE_PATH_KAFKA}
    image: ias-kafka-image

  alma-weather-plugin:
    container_name: ias-prod-alma-weather-plugin
    image: registry.inria.cl:5000/alma-weather-plugin:prod
    links:
      - ${KAFKA_SERVER}
    command: "${KAFKA_SERVER} 9092"

  converter:
    container_name: ias-prod-converter
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - ${KAFKA_SERVER}
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
    command: "iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  supervisor:
    container_name: ias-prod-supervisor
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - ${KAFKA_SERVER}
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
    command: "iasSupervisor SupervisorID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-prod-sender
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - ${KAFKA_SERVER}
    command: "iasRun -l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8001/core/ org.eso.ias.webserversender.WebServerSender WebServerSenderID"

  webserver:
    container_name: ias-prod-webserver
    image: registry.inria.cl:5000/ias-webserver:prod
    command: ./runserver.sh

  display:
    container_name: ias-prod-display
    image: registry.inria.cl:5000/ias-display:prod

  nginx:
    container_name: ias-prod
    build: ${DOCKERFILE_PATH_NGINX}
    image: ias-nginx-image
    volumes_from:
     - display
     - webserver
    ports:
      - "80:80"
