version: "2"

services:
  kafka:
    container_name: ias-kafka
    image: registry.inria.cl:5000/ias-core:dev
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092
    volumes:
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_kafka.sh"

  alma-weather-plugin:
    container_name: ias-dev-alma-weather-plugin
    image: registry.inria.cl:5000/alma-weather-plugin:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  visual-inspection-plugin:
    container_name: ias-dev-visual-inspection
    image: registry.inria.cl:5000/visual-inspection-plugin:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
    - ${LOGS_PATH}:/usr/src/weather_visual_inspection_plugin/logs/
    - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/weather_visual_inspection_plugin/input
    command: ["-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092", "-f input/inspections.json"]

  dummy-plugin:
    container_name: ias-dev-dummy-plugin
    image: registry.inria.cl:5000/ias-dummy-plugin:dev
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "dummy ${KAFKA_SERVER} 9092"

  dummy-plugin-21:
    container_name: ias-dev-dummy-plugin-21
    image: registry.inria.cl:5000/ias-dummy-plugin:dev
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "dummy-21 ${KAFKA_SERVER} 9092"

  dummy-plugin-22:
    container_name: ias-dev-dummy-plugin-22
    image: registry.inria.cl:5000/ias-dummy-plugin:dev
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "dummy-22 ${KAFKA_SERVER} 9092"

  converter:
    container_name: ias-dev-converter
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  weather-supervisor:
    container_name: ias-dev-weather-supervisor
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor Supervisor-Weather -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  antennas-supervisor:
    container_name: ias-dev-antennas-supervisor
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor Supervisor-Antennas -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  dummy-supervisor:
    container_name: ias-dev-dummy-supervisor
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor SupervisorDummy -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-dev-sender
    image: registry.inria.cl:5000/ias-core:dev
    environment:
      - WS_CONNECTION_PASS=${WS_CONNECTION_PASS}
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasWebServerSender WebServerSenderID -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8000/core/ -jcdb /usr/src/cdb/ -t ALARM -i Array-AntennasToPads"

  ltdb-connector:
    container_name: ias-dev-ltdb-connector
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=${KAFKA_SERVER}
      - KAFKA_PORT=9092
      - CASSANDRA_HOST=${CASSANDRA_SERVER}
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ltdb_connector.sh"

  mail-sender:
    container_name: ias-dev-mail-sender
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasMailSender MailSenderID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  webserver:
    container_name: ias-dev-webserver
    image: registry.inria.cl:5000/ias-webserver:dev
    command: ./runserver.sh
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OP_DUTY_PASSWORD=${OP_DUTY_PASSWORD}
      - PROCESS_CONNECTION_PASS=${WS_CONNECTION_PASS}
    volumes:
      - ${DOCKERFILE_PATH_PRIVATE_FILES}:/usr/src/ias-webserver/private_files
      - ${CDB_PATH}/CDB:/usr/src/ias-webserver/CDB
      - ${LOGS_PATH}:/usr/src/ias-webserver/logs

  visual-inspection-webserver:
    container_name: ias-dev-visual-inspection-webserver
    image: registry.inria.cl:5000/visual-inspection:dev
    command: ./runserver.sh
    volumes:
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/visual-inspection/output

  display:
    container_name: ias-dev-display
    image: registry.inria.cl:5000/ias-display:dev

  nginx:
    container_name: ias-dev-nginx
    build: ${DOCKERFILE_PATH_NGINX}
    volumes_from:
      - display
      - webserver
      - visual-inspection-webserver
    links:
      - display
      - webserver
      - visual-inspection-webserver
    depends_on:
      - display
      - webserver
      - visual-inspection-webserver
    ports:
      - "80:80"
