version: "2"

services:
  kafka:
    container_name: ias-kafka
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092
    volumes:
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_kafka.sh"

  alma-weather-plugin:
    container_name: ias-build-alma-weather-plugin
    build:
      context: ${DOCKERFILE_PATH_ALMA_WEATHER}
      dockerfile: Dockerfile-build
    image: ias-build-alma-weather-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  visual-inspection-plugin:
    container_name: ias-build-visual-inspection
    build:
      context: ${DOCKERFILE_PATH_VISUAL_INSPECTION}
      dockerfile: Dockerfile-build
    image: ias-build-visual-inspection-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/weather_visual_inspection_plugin/logs/
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/weather_visual_inspection_plugin/input
    command: ["-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092", "-f input/inspections.json"]

  dummy-plugin:
    container_name: ias-build-dummy-plugin
    build:
      context: ${DOCKERFILE_PATH_DUMMY_PLUGIN}
      dockerfile: Dockerfile-build
    image: ias-build-dummy-plugin-image
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "dummy ${KAFKA_SERVER} 9092"

  converter:
    container_name: ias-build-converter
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  weather-supervisor:
    container_name: ias-build-weather-supervisor
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor Supervisor-Weather -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  antennas-supervisor:
    container_name: ias-build-antennas-supervisor
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor Supervisor-Antennas -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  dummy-supervisor:
    container_name: ias-build-dummy-supervisor
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor SupervisorDummy -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-build-sender
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    environment:
      - WS_CONNECTION_PASS=${WS_CONNECTION_PASS}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasWebServerSender WebServerSenderID -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8000/core/ -jcdb /usr/src/cdb/ -t ALARM -i Array-AntennasToPads"

  ltdb-connector:
    container_name: ias-build-ltdb-connector
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=${KAFKA_SERVER}
      - KAFKA_PORT=9092
      - CASSANDRA_HOST=${CASSANDRA_SERVER}
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ltdb_connector.sh"

  mail-sender:
    container_name: ias-build-mail-sender
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasMailSender MailSenderID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  monitor:
    container_name: ias-build-monitor
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasMonitor MonitorID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  webserver:
    container_name: ias-build-webserver
    build: ${DOCKERFILE_PATH_WEBSERVER}
    image: ias-build-webserver-image
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OP_DUTY_PASSWORD=${OP_DUTY_PASSWORD}
      - PROCESS_CONNECTION_PASS=${WS_CONNECTION_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
    volumes:
      - ${DOCKERFILE_PATH_PRIVATE_FILES}:/usr/src/ias-webserver/private_files
      - ${CDB_PATH}/CDB:/usr/src/ias-webserver/CDB
      - ${LOGS_PATH}:/usr/src/ias-webserver/logs
    command: ./runserver.sh

  visual-inspection-webserver:
    container_name: ias-build-visual-inspection-webserver
    build: ${DOCKERFILE_PATH_VISUAL_INSPECTION_WEBSERVER}
    image: ias-build-visual-inspection-webserver-image
    command: ./runserver.sh
    volumes:
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/visual-inspection/output

  display:
    container_name: ias-build-display
    image: ias-build-display-image
    build: ${DOCKERFILE_PATH_DISPLAY}

  nginx:
    container_name: ias-nginx
    build: ${DOCKERFILE_PATH_NGINX}
    image: ias-nginx-image
    volumes_from:
      - display
      - webserver
      - visual-inspection-webserver
    links:
      - display
      - webserver
      - visual-inspection-webserver
    depends_on:
      - display
      - webserver
      - visual-inspection-webserver
    ports:
      - "80:80"
