version: "2"

services:
  kafka:
    container_name: ias-kafka
    image: alarmsystem/ias-kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092

  alma-weather-plugin:
    container_name: ias-build-alma-weather-plugin
    build:
      context: ${DOCKERFILE_PATH_ALMA_WEATHER}
      dockerfile: Dockerfile-build
    image: ias-build-alma-weather-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  visual-inspection-plugin:
    container_name: ias-build-visual-inspection
    build:
      context: ${DOCKERFILE_PATH_VISUAL_INSPECTION}
      dockerfile: Dockerfile-build
    image: ias-build-visual-inspection-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/weather_visual_inspection_plugin/logs/
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/weather_visual_inspection_plugin/input
    command: ["-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092", "-f input/inspections.json"]

  dummy-plugin:
    container_name: ias-build-dummy-plugin
    build:
      context: ${DOCKERFILE_PATH_DUMMY_PLUGIN}
      dockerfile: Dockerfile-build
    image: ias-build-dummy-plugin-image
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "${KAFKA_SERVER} 9092"

  dummy-antennas-pad:
    container_name: ias-build-dummy-antennas-pad
    build:
      context: ${DOCKERFILE_PATH_DUMMY_ANTENNAS_PAD}
      dockerfile: Dockerfile
    image: ias-build-dummy-antennas-pad-image
    links:
      - kafka
    depends_on:
      - kafka
    command: "${KAFKA_SERVER}:9092"


  converter:
    container_name: ias-build-converter
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  weather-supervisor:
    container_name: ias-build-weather-supervisor
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor Supervisor-Weather -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  antennas-supervisor:
    container_name: ias-build-antennas-supervisor
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor Supervisor-Antennas -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  dummy-supervisor:
    container_name: ias-build-dummy-supervisor
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
    command: "iasSupervisor SupervisorDummy -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-build-sender
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "iasRun -l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8001/core/ org.eso.ias.webserversender.WebServerSender WebServerSenderID -jcdb /usr/src/cdb/"

  webserver:
    container_name: ias-build-webserver
    build: ${DOCKERFILE_PATH_WEBSERVER}
    image: ias-build-webserver-image
    command: ./runserver.sh
    volumes:
      - ${DOCKERFILE_PATH_PRIVATE_FILES}:/usr/src/ias-webserver/private_files

  display:
    container_name: ias-build-display
    image: ias-build-display-image
    build: ${DOCKERFILE_PATH_DISPLAY}

  nginx:
    container_name: ias-nginx
    build: ${DOCKERFILE_PATH_NGINX}
    image: ias-nginx-image
    volumes_from:
      - display
      - webserver
    links:
      - display
      - webserver
    depends_on:
      - display
      - webserver
    ports:
      - "80:80"
