version: "2"

services:
  kafka:
    container_name: ias-kafka
    image: registry.inria.cl:5000/ias-core:prod
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092
    volumes:
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_kafka.sh"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  alma-weather-plugin:
    container_name: ias-prod-alma-weather-plugin
    image: registry.inria.cl:5000/alma-weather-plugin:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  visual-inspection-plugin:
    container_name: ias-prod-visual-inspection
    image: registry.inria.cl:5000/visual-inspection-plugin:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
    - ${LOGS_PATH}:/usr/src/weather_visual_inspection_plugin/logs/
    - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/weather_visual_inspection_plugin/input
    command: ["-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092", "-f input/inspections.json"]

  converter:
    container_name: ias-prod-converter
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  weather-supervisor:
    container_name: ias-prod-weather-supervisor
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor Supervisor-Weather -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  antennas-supervisor:
    container_name: ias-prod-antennas-supervisor
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor Supervisor-Antennas -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-prod-sender
    image: registry.inria.cl:5000/ias-core:prod
    environment:
      - WS_CONNECTION_PASS=${WS_CONNECTION_PASS}
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasWebServerSender WebServerSenderID -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8000/core/ -jcdb /usr/src/cdb/ -t ALARM -i Array-AntennasToPads"

  ltdb-connector:
    container_name: ias-prod-ltdb-connector
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=${KAFKA_SERVER}
      - KAFKA_PORT=9092
      - CASSANDRA_HOST=${CASSANDRA_SERVER}
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ltdb_connector.sh"

  mail-sender:
    container_name: ias-prod-mail-sender
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasMailSender MailSenderID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  monitor:
    container_name: ias-prod-monitor
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasMonitor MonitorID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  webserver:
    container_name: ias-prod-webserver
    image: registry.inria.cl:5000/ias-webserver:prod
    links:
      - redis
    depends_on:
      - redis
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OP_DUTY_PASSWORD=${OP_DUTY_PASSWORD}
      - PROCESS_CONNECTION_PASS=${WS_CONNECTION_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - ${DOCKERFILE_PATH_PRIVATE_FILES}:/usr/src/ias-webserver/private_files
      - ${CDB_PATH}/CDB:/usr/src/ias-webserver/CDB
      - ${LOGS_PATH}:/usr/src/ias-webserver/logs
    command: ./runserver.sh

  visual-inspection-webserver:
    container_name: ias-prod-visual-inspection-webserver
    image: registry.inria.cl:5000/visual-inspection:prod
    command: ./runserver.sh
    volumes:
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/visual-inspection/output

  display:
    container_name: ias-prod-display
    image: registry.inria.cl:5000/ias-display:prod

  nginx:
    container_name: ias-prod-nginx
    build: ${DOCKERFILE_PATH_NGINX}
    volumes_from:
      - display
      - webserver
      - visual-inspection-webserver
    links:
      - display
      - webserver
      - visual-inspection-webserver
    depends_on:
      - display
      - webserver
      - visual-inspection-webserver
    ports:
      - "80:80"
