version: "2"

services:
  webserver:
    container_name: ias-build-webserver
    build: ${DOCKERFILE_PATH_WEBSERVER}
    image: ias-build-webserver-image
    command: ./runserver.sh
    volumes:
      - ${DOCKERFILE_PATH_PRIVATE_FILES}:/usr/src/ias-webserver/private_files
      - ${CDB_PATH}/CDB:/usr/src/ias-webserver/CDB
      - ${LOGS_PATH}:/usr/src/ias-webserver/logs

  visual-inspection-webserver:
    container_name: ias-build-visual-inspection-webserver
    build: ${DOCKERFILE_PATH_VISUAL_INSPECTION_WEBSERVER}
    image: ias-build-visual-inspection-webserver-image
    command: ./runserver.sh
    volumes:
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/visual-inspection/output

  display:
    container_name: ias-build-display
    image: ias-build-display-image
    build: ${DOCKERFILE_PATH_DISPLAY}

  nginx:
    container_name: ias-nginx
    build: ${DOCKERFILE_PATH_NGINX}
    image: ias-nginx-image
    volumes_from:
      - display
      - webserver
      - visual-inspection-webserver
    links:
      - display
      - webserver
      - visual-inspection-webserver
    depends_on:
      - display
      - webserver
      - visual-inspection-webserver
    ports:
      - "80:80"
