version: "2"

services:
  kafka:
    container_name: ias-kafka
    image: alarmsystem/ias-kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092

  alma-weather-plugin:
    container_name: ias-build-alma-weather-plugin
    build:
      context: ${DOCKERFILE_PATH_ALMA_WEATHER}
      dockerfile: Dockerfile-build
    image: ias-build-alma-weather-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  converter:
    container_name: ias-build-converter
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  supervisor:
    container_name: ias-build-supervisor
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "iasSupervisor SupervisorID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-build-sender
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "iasRun -l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8001/core/ org.eso.ias.webserversender.WebServerSender WebServerSenderID -jcdb /usr/src/cdb/"

  webserver:
    container_name: ias-build-webserver
    build: ${DOCKERFILE_PATH_WEBSERVER}
    image: ias-build-webserver-image
    command: ./runserver.sh

  display:
    container_name: ias-build-display
    image: ias-build-display-image
    build: ${DOCKERFILE_PATH_DISPLAY}

  nginx:
    container_name: ias-nginx
    build: ${DOCKERFILE_PATH_NGINX}
    image: ias-nginx-image
    volumes_from:
      - display
      - webserver
    links:
      - display
      - webserver
    depends_on:
      - display
      - webserver
    ports:
      - "80:80"
