version: "2"

services:
  kafka:
    image: spotify/kafka:latest

  cdb:
    image: cdb:latest

  alma-weather-plugin:
    image: alma-weather-plugin:latest
    links:
      - ${KAFKA_SERVER}
    command: "${KAFKA_SERVER} 9092"

  dummy-plugin:
    image: dummy-plugin:latest
    stdin_open: true
    tty: true
    links:
      - ${KAFKA_SERVER}
    command: "${KAFKA_SERVER} 9092"

  converter:
    image: ias:latest
    links:
      - ${KAFKA_SERVER}
    volumes_from:
      - cdb
    command: "-l s -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092 org.eso.ias.converter.Converter ConverterID -jcdb /usr/src/cdb/"

  supervisor:
    image: ias:latest
    links:
      - ${KAFKA_SERVER}
    volumes_from:
      - cdb
    command: "-l s -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092 org.eso.ias.supervisor.Supervisor SupervisorID -jcdb /usr/src/cdb/"

  dummy-supervisor:
    image: ias:latest
    links:
      - ${KAFKA_SERVER}
    volumes_from:
      - cdb
    command: "-l s -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092 org.eso.ias.supervisor.Supervisor SupervisorDummy -jcdb /usr/src/cdb/"

  sender:
    image: ias:latest
    links:
      - ${KAFKA_SERVER}
    volumes_from:
      - cdb
    command: "-l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8001/core/ org.eso.ias.webserversender.WebServerSender WebServerSenderID"

  webserver:
    image: ias-webserver:latest

  display:
    image: ias-display:latest

  nginx:
    build: ./nginx
    volumes_from:
     - display
     - webserver
    ports:
      - "80:80"
