version: "2"

services:

  kafka:
    image: spotify/kafka:latest

  cdb:
    image: cdb:latest
    volumes:
      - "/tmp/cdb:/usr/src/cdb/CDB"

  alma-weather-plugin:
    image: alma-weather-plugin:latest
    links:
        - "kafka"

  ias-converter:
    image: ias:latest
    links:
      - "kafka"
    volumes:
      - "/tmp/cdb:/CDB"
    command: "-l s -Dorg.eso.ias.converter.kafka.servers=kafka:9092 org.eso.ias.converter.Converter ConverterID -jcdb /"

  ias-supervisor:
    image: ias:latest
    links:
      - "kafka"
    volumes:
      - "/tmp/cdb:/CDB"
    command: "-l s -Dorg.eso.ias.kafka.brokers=kafka:9092 org.eso.ias.supervisor.Supervisor SupervisorID -jcdb /"

  display:
    image: ias-display:latest

  nginx:
    build: ./nginx
    volumes_from:
     - display
    ports:
      - "80:80"
