version: "2"

services:
  kafka:
    image: spotify/kafka:latest

  cdb:
    build: ${DOCKERFILE_PATH_CDB}

  alma-weather-plugin:
    build:
      context: ${DOCKERFILE_PATH_ALMA_WEATHER}
      dockerfile: Dockerfile.dev
    links:
      - ${KAFKA_SERVER}
    command: "${KAFKA_SERVER} 9092"

  dummy-plugin:
    build: ${DOCKERFILE_PATH_DUMMY_PLUGIN}
    stdin_open: true
    tty: true
    links:
      - ${KAFKA_SERVER}
    command: "${KAFKA_SERVER} 9092"

  converter:
    build: ${DOCKERFILE_PATH_CORE}
    links:
      - ${KAFKA_SERVER}
    volumes_from:
      - cdb
    command: "-l s -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092 org.eso.ias.converter.Converter ConverterID -jcdb /usr/src/cdb/"

  supervisor:
    build: ${DOCKERFILE_PATH_CORE}
    links:
      - ${KAFKA_SERVER}
    volumes_from:
      - cdb
    command: "-l s -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092 org.eso.ias.supervisor.Supervisor SupervisorID -jcdb /usr/src/cdb/"

  dummy-supervisor:
    build: ${DOCKERFILE_PATH_CORE}
    links:
      - ${KAFKA_SERVER}
    volumes_from:
      - cdb
    command: "-l s -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092 org.eso.ias.supervisor.Supervisor SupervisorDummy -jcdb /usr/src/cdb/"

  sender:
    build: ${DOCKERFILE_PATH_CORE}
    links:
      - ${KAFKA_SERVER}
    volumes_from:
      - cdb
    command: "-l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8001/core/ org.eso.ias.webserversender.WebServerSender WebServerSenderID"

  webserver:
    build: ${DOCKERFILE_PATH_WEBSERVER}

  display:
    build: ${DOCKERFILE_PATH_DISPLAY}

  nginx:
    build: ./nginx
    volumes_from:
     - display
     - webserver
    ports:
      - "80:80"
