version: "2"

services:
  alma-weather-plugin:
    image: alma-weather-plugin:latest
    links:
        - "kafka"
        
  kafka:
    image: spotify/kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"

  ias-core:
    image: ias:latest
    links:
      - "kafka"
    volumes:
      - "/tmp/cdb:/CDB"

  cdb:
    image: cdb:latest
    volumes:
      - "/tmp/cdb:/usr/src/cdb/CDB"

  display:
    image: ias-display:latest

  nginx:
    build: ./nginx
    volumes_from:
     - display
    ports:
      - "80:80"
