version: "2"

services:
  kafka:
    container_name: ias-kafka
    image: alarmsystem/ias-kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092

  alma-weather-plugin:
    container_name: ias-dev-alma-weather-plugin
    image: registry.inria.cl:5000/alma-weather-plugin:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - logs-volume:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  dummy-plugin:
    container_name: ias-dev-dummy-plugin
    image: registry.inria.cl:5000/ias-dummy-plugin:dev
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "${KAFKA_SERVER} 9092"

  converter:
    container_name: ias-dev-converter
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  supervisor:
    container_name: ias-dev-supervisor
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor SupervisorID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  weather-supervisor:
    container_name: ias-dev-weather-supervisor
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor Supervisor-Weather -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  dummy-supervisor:
    container_name: ias-dev-dummy-supervisor
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor SupervisorDummy -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-dev-sender
    image: registry.inria.cl:5000/ias-core:dev
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasRun -l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8001/core/ org.eso.ias.webserversender.WebServerSender WebServerSenderID -jcdb /usr/src/cdb/"

  webserver:
    tty: true
    container_name: ias-mount-webserver
    build:
      context: ${DOCKERFILE_PATH_WEBSERVER}
      dockerfile: Dockerfile-dev
    volumes:
      - ${DOCKERFILE_PATH_WEBSERVER}:/usr/src/ias-webserver
    command: "./runserver-dev.sh"

  nginx:
    container_name: ias-nginx-local-disp
    build:
      context: ${DOCKERFILE_PATH_NGINX}
      dockerfile: Dockerfile-local-display
    volumes_from:
      - webserver
    links:
      - webserver
    depends_on:
      - webserver
    ports:
      - "80:80"
      - "8001:8001"
      - "8000:8000"

volumes:
  logs-volume:
