version: "2"

services:
  kafka:
    container_name: ias-kafka
    image: alarmsystem/ias-kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092

  alma-weather-plugin:
    container_name: ias-build-alma-weather-plugin
    build:
      context: ${DOCKERFILE_PATH_ALMA_WEATHER}
      dockerfile: Dockerfile-build
    image: ias-build-alma-weather-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - logs-volume:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  dummy-plugin:
    container_name: ias-build-dummy-plugin
    build:
      context: ${DOCKERFILE_PATH_DUMMY_PLUGIN}
      dockerfile: Dockerfile-build
    image: ias-build-dummy-plugin-image
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "${KAFKA_SERVER} 9092"

  converter:
    container_name: ias-build-converter
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  weather-supervisor:
    container_name: ias-build-weather-supervisor
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor Supervisor-Weather -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  dummy-supervisor:
    container_name: ias-build-dummy-supervisor
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor SupervisorDummy -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-build-sender
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasRun -l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8001/core/ org.eso.ias.webserversender.WebServerSender WebServerSenderID -jcdb /usr/src/cdb/"

  webserver:
    tty: true
    container_name: ias-mount-webserver
    build:
      context: ${DOCKERFILE_PATH_WEBSERVER}
      dockerfile: Dockerfile-dev
    image: ias-mount-webserver-image
    volumes:
      - ${DOCKERFILE_PATH_WEBSERVER}:/usr/src/ias-webserver
      - ${DOCKERFILE_PATH_PRIVATE_FILES}:/usr/src/ias-webserver/private_files
    command: "./runserver-dev.sh"

  display:
    container_name: ias-mount-display
    build:
      context: ${DOCKERFILE_PATH_DISPLAY}
      dockerfile: Dockerfile-dev
    image: ias-mount-display-image
    volumes:
      - ${DOCKERFILE_PATH_DISPLAY}:/usr/src/ias-display
      - ./node_modules:/usr/src/ias-display/node_modules
    command: "./runserver-dev.sh"

  nginx:
    container_name: ias-nginx-dev-server
    build:
      context: ${DOCKERFILE_PATH_NGINX}
      dockerfile: Dockerfile-dev
    image: ias-nginx-dev-server-image
    volumes_from:
      - display
      - webserver
    links:
      - display
      - webserver
    depends_on:
      - display
      - webserver
    ports:
      - "80:80"

volumes:
  logs-volume:
