version: "2"

services:
  kafka:
    container_name: ias-kafka
    image: alarmsystem/ias-kafka:latest

  alma-weather-plugin:
    container_name: ias-prod-alma-weather-plugin
    image: registry.inria.cl:5000/alma-weather-plugin:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - logs-volume:/usr/src/alma_weather_plugin/logs/
    command: "${KAFKA_SERVER} 9092"

  dummy-plugin:
    container_name: ias-prod-dummy-plugin
    image: registry.inria.cl:5000/ias-dummy-plugin:prod
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "${KAFKA_SERVER} 9092"

  converter:
    container_name: ias-prod-converter
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  supervisor:
    container_name: ias-prod-supervisor
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor SupervisorID -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  dummy-supervisor:
    container_name: ias-prod-dummy-supervisor
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor SupervisorDummy -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-prod-sender
    image: registry.inria.cl:5000/ias-core:prod
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - logs-volume:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasRun -l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8001/core/ org.eso.ias.webserversender.WebServerSender WebServerSenderID -jcdb /usr/src/cdb/"

  webserver:
    container_name: ias-dev-webserver
    image: registry.inria.cl:5000/ias-webserver:dev
    command: ./runserver.sh

  display:
    container_name: ias-dev-display
    image: registry.inria.cl:5000/ias-display:dev

  nginx:
    container_name: ias-nginx
    build: ${DOCKERFILE_PATH_NGINX}
    volumes_from:
      - display
      - webserver
    links:
      - display
      - webserver
    depends_on:
      - display
      - webserver
    ports:
      - "80:80"

volumes:
  logs-volume:
