version: "2"

services:
  kafka:
    container_name: ias-kafka
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092
    volumes:
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_kafka.sh"

  alma-weather-plugin:
    container_name: ias-build-alma-weather-plugin
    build:
      context: ${DOCKERFILE_PATH_ALMA_WEATHER}
      dockerfile: Dockerfile-build
    image: ias-build-alma-weather-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  visual-inspection-plugin:
    container_name: ias-build-visual-inspection
    build:
      context: ${DOCKERFILE_PATH_VISUAL_INSPECTION}
      dockerfile: Dockerfile-build
    image: ias-build-visual-inspection-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/weather_visual_inspection_plugin/logs/
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/weather_visual_inspection_plugin/input
    command: ["-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092", "-f input/inspections.json"]

  dummy-plugin:
    container_name: ias-build-dummy-plugin
    build:
      context: ${DOCKERFILE_PATH_DUMMY_PLUGIN}
      dockerfile: Dockerfile-build
    image: ias-build-dummy-plugin-image
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "dummy ${KAFKA_SERVER} 9092"

  dummy-plugin-21:
    container_name: ias-build-dummy-plugin-21
    build:
      context: ${DOCKERFILE_PATH_DUMMY_PLUGIN}
      dockerfile: Dockerfile-build
    image: ias-build-dummy-plugin-image
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "dummy-21 ${KAFKA_SERVER} 9092"

  dummy-plugin-22:
    container_name: ias-build-dummy-plugin-22
    build:
      context: ${DOCKERFILE_PATH_DUMMY_PLUGIN}
      dockerfile: Dockerfile-build
    image: ias-build-dummy-plugin-image
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "dummy-22 ${KAFKA_SERVER} 9092"

  mock-kafka-publisher:
    container_name: ias-build-mock-kafka-publisher
    build:
      context: ${DOCKERFILE_PATH_DUMMY_ANTENNAS_PAD}
      dockerfile: Dockerfile
    image: ias-build-mock-kafka-publisher-image
    links:
      - kafka
    depends_on:
      - kafka
    command: "${KAFKA_SERVER}:9092"

  converter:
    container_name: ias-build-converter
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  weather-supervisor:
    container_name: ias-build-weather-supervisor
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor Supervisor-Weather -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  antennas-supervisor:
    container_name: ias-build-antennas-supervisor
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor Supervisor-Antennas -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  dummy-supervisor:
    container_name: ias-build-dummy-supervisor
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasSupervisor SupervisorDummy -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  sender:
    container_name: ias-build-sender
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./docker_run_ias.sh iasWebServerSender WebServerSenderID -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8000/core/ -jcdb /usr/src/cdb/ -t ALARM -i Array-AntennasToPads"

  ltdb-connector:
    container_name: ias-build-ltdb-connector
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./dokcer_run_ias.sh iasLTDBConnector"

  webserver:
    tty: true
    container_name: ias-mount-webserver
    build:
      context: ${DOCKERFILE_PATH_WEBSERVER}
      dockerfile: Dockerfile-dev
    volumes:
      - ${DOCKERFILE_PATH_WEBSERVER}:/usr/src/ias-webserver
      - ${DOCKERFILE_PATH_PRIVATE_FILES}:/usr/src/ias-webserver/private_files
      - ${CDB_PATH}/CDB:/usr/src/ias-webserver/CDB
      - ${LOGS_PATH}:/usr/src/ias-webserver/logs
    command: "./runserver-dev.sh"

  visual-inspection-webserver:
    tty: true
    container_name: ias-mount-visual-inspection-webserver
    build:
      context: ${DOCKERFILE_PATH_VISUAL_INSPECTION_WEBSERVER}
      dockerfile: Dockerfile-dev
    image: ias-mount-visual-inspection-webserver-image
    command: "./runserver-dev.sh"
    volumes:
      - ${DOCKERFILE_PATH_VISUAL_INSPECTION_WEBSERVER}:/usr/src/visual-inspection
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/visual-inspection/output

  nginx:
    container_name: ias-nginx-local-disp
    build:
      context: ${DOCKERFILE_PATH_NGINX}
      dockerfile: Dockerfile-local-display
    volumes_from:
      - webserver
      - visual-inspection-webserver
    links:
      - webserver
      - visual-inspection-webserver
    depends_on:
      - webserver
      - visual-inspection-webserver
    ports:
      - "80:80"
      - "8000:8000"
