version: "2"

services:
  kafka:
    container_name: ias-kafka
    image: alarmsystem/ias-kafka:latest
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - ADVERTISED_HOST=${EXPOSED_KAFKA_SERVER}
      - ADVERTISED_PORT=9092

  alma-weather-plugin:
    container_name: ias-build-alma-weather-plugin
    build:
      context: ${DOCKERFILE_PATH_ALMA_WEATHER}
      dockerfile: Dockerfile-build
    image: ias-build-alma-weather-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/alma_weather_plugin/logs/
    command: "-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092"

  visual-inspection-plugin:
    container_name: ias-build-visual-inspection
    build:
      context: ${DOCKERFILE_PATH_VISUAL_INSPECTION}
      dockerfile: Dockerfile-build
    image: ias-build-visual-inspection-plugin-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${LOGS_PATH}:/usr/src/weather_visual_inspection_plugin/logs/
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/weather_visual_inspection_plugin/input
    command: ["-Dorg.eso.ias.plugins.kafka.server=${KAFKA_SERVER}:9092", "-f input/inspections.json"]

  dummy-plugin:
    container_name: ias-build-dummy-plugin
    build:
      context: ${DOCKERFILE_PATH_DUMMY_PLUGIN}
      dockerfile: Dockerfile-build
    image: ias-build-dummy-plugin-image
    stdin_open: true
    tty: true
    links:
      - kafka
    depends_on:
      - kafka
    command: "${KAFKA_SERVER} 9092"

  mock-kafka-publisher:
    container_name: ias-build-mock-kafka-publisher
    build:
      context: ${DOCKERFILE_PATH_DUMMY_ANTENNAS_PAD}
      dockerfile: Dockerfile
    image: ias-build-mock-kafka-publisher-image
    links:
      - kafka
    depends_on:
      - kafka
    command: "${KAFKA_SERVER}:9092"

  converter:
    container_name: ias-build-converter
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasConverter ConverterID -jcdb /usr/src/cdb/ -Dorg.eso.ias.converter.kafka.servers=${KAFKA_SERVER}:9092"

  weather-supervisor:
    container_name: ias-build-weather-supervisor
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor Supervisor-Weather -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  antennas-supervisor:
    container_name: ias-build-antennas-supervisor
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor Supervisor-Antennas -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  dummy-supervisor:
    container_name: ias-build-dummy-supervisor
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasSupervisor SupervisorDummy -jcdb /usr/src/cdb/ -Dorg.eso.ias.kafka.brokers=${KAFKA_SERVER}:9092"

  alarms-sender:
    container_name: ias-build-alarms-sender
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasRun -l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8000/core/ org.eso.ias.webserversender.WebServerSender WebServerAlarmsSenderID -jcdb /usr/src/cdb/ -t ALARM"

  values-sender:
    container_name: ias-build-values-sender
    build: ${DOCKERFILE_PATH_CORE}
    image: ias-build-core-image
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${LOGS_PATH}:/usr/src/IntegratedAlarmSystemRoot/logs
    command: "iasRun -l s -Dorg.eso.ias.senders.kafka.servers=${KAFKA_SERVER}:9092 -Dorg.eso.ias.senders.webserver.uri=ws://webserver:8000/core/ org.eso.ias.webserversender.WebServerSender WebServerValuesSenderID -jcdb /usr/src/cdb/ -i Array-AntennasToPads"

  webserver:
    tty: true
    container_name: ias-mount-webserver
    build:
      context: ${DOCKERFILE_PATH_WEBSERVER}
      dockerfile: Dockerfile-dev
    volumes:
      - ${DOCKERFILE_PATH_WEBSERVER}:/usr/src/ias-webserver
      - ${DOCKERFILE_PATH_PRIVATE_FILES}:/usr/src/ias-webserver/private_files
      - ${CDB_PATH}/CDB:/usr/src/ias-webserver/CDB
    command: "./runserver-dev.sh"

  visual-inspection-webserver:
    tty: true
    container_name: ias-mount-visual-inspection-webserver
    build:
      context: ${DOCKERFILE_PATH_VISUAL_INSPECTION_WEBSERVER}
      dockerfile: Dockerfile-dev
    image: ias-mount-visual-inspection-webserver-image
    command: "./runserver-dev.sh"
    volumes:
      - ${DOCKERFILE_PATH_VISUAL_INSPECTION_WEBSERVER}:/usr/src/visual-inspection
      - ${VISUAL_INSPECTION_FILE_PATH}:/usr/src/visual-inspection/output

  nginx:
    container_name: ias-nginx-local-disp
    build:
      context: ${DOCKERFILE_PATH_NGINX}
      dockerfile: Dockerfile-local-display
    volumes_from:
      - webserver
      - visual-inspection-webserver
    links:
      - webserver
      - visual-inspection-webserver
    depends_on:
      - webserver
      - visual-inspection-webserver
    ports:
      - "80:80"
      - "8000:8000"
