version: "2"

services:

  ias:
    container_name: iascompilebuild
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./compile_component.sh"

  converter:
    container_name: ias-build-compileerter
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./compile_component.sh Converter"

  supervisor:
    container_name: ias-build-compilevisor
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./compile_component.sh Supervisor"

  dasu:
    container_name: ias-compile-dasu
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./compile_component.sh DistributedUnit"

  asce:
    container_name: ias-compile-asce
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./compile_component.sh CompElement"

  sender:
    container_name: ias-build-compileender
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./compile_component.sh WebServerSender"

  tf:
    container_name: ias-compileld-tf
    build:
      context: ${DOCKERFILE_PATH_CORE}
      dockerfile: Dockerfile-no-build
    image: ias-build-core-image
    volumes:
      - ${CDB_PATH}:/usr/src/cdb
      - ${IAS_ROOT_PATH}:/usr/src/IntegratedAlarmSystemRoot
    command: "./compile_component.sh TransferFunctions"
